---
- name: 'Add MongoDB apt key'
  tags: 'mongodb'
  sudo: 'yes'
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 9DA31620334BD75D9DCB49F368818C72E52529D4

- name: 'Add MongoDB apt repository'
  tags: 'mongodb'
  sudo: 'yes'
  apt_repository:
    repo: 'deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse'
    state: present

- name: 'Install MongoDB'
  tags: 'mongodb'
  sudo: 'yes'
  apt:
    name: mongodb-org
    state: present
    update_cache: true

- name: 'Ensure backup script directory exists'
  tags: 'mongodb'
  sudo: 'yes'
  file:
    path: {{ mongodb_backup_script_dir }}
    state: directory
    owner: root
    group: backup
  when:
    - mongodb_backup_frequency != 'never'

- name: 'Install backup script'
  tags: 'mongodb'
  sudo: 'yes'
  template:
    src: mongo_dump.sh
    dest: {{ mongodb_backup_script_dir }}/{{ mongodb_backup_script_filename }}
    owner: root
    group: backup
  when:
    - mongodb_backup_frequency != 'never'

- name: 'Set up cron job for automated backups'
  tags: 'mongodb'
  sudo: 'yes'
  cron:
    name: "{{ mongodb_backup_cron_name }}"
    special_time: "{{ mongodb_backup_frequency }}"
    job: "sh {{ mongodb_backup_script_dir }}/{{ mongodb_backup_script_filename }}"
  when:
    - mongodb_backup_frequency != 'never'